[build-system]
requires = ["poetry-core==2.4.1"]
build-backend = "poetry.core.masonry.api"

[project]
name = "keystone-api-client"
version = "0.0.0"
readme = "README.md"
description = "Python client for the Keystone API"
authors = [{ name = "Better HPC LLC" }]
keywords = ["Better", "HPC", "keystone", "api", "client"]
packages = [{ include = "keystone_client" }]
requires-python = ">=3.11,<4"
classifiers = [
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Typing :: Typed"
]
dependencies = [
    "httpx>=0.28.1",
]

[project.optional-dependencies]
dev = ["coverage==7.15.2", ]

[tool.coverage.run]
source = ["keystone_client"]
branch = true
omit = [
    "*/tests/*",
]
