name: 🤖 Publish Package

on:
  workflow_call:
    inputs:
      version:
        description: 'Set the version number of the published application.'
        default: '0.0.0'
        required: false
        type: string

jobs:
  publish-pypi:
    name: Python Distribution
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Fetch build artifact
        uses: actions/download-artifact@v4
        with:
          name: keystone-client-python
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          user: ${{ secrets.REPO_USER }}
          password: ${{ secrets.REPO_PASSWORD }}
