name: 🤖 Publish Package

on:
  workflow_call:
    inputs:
      version:
        description: 'Set the version number of the published application.'
        default: '0.0.0'
        required: false
        type: string

jobs:
  publish-pypi:
    name: Python Distribution
    runs-on: ubuntu-latest

    environment:
      name: cloudsmith
      url: https://app.cloudsmith.com/better-hpc/keystone-api-client

    steps:
      - name: Fetch build artifact
        uses: actions/download-artifact@v5
        with:
          name: keystone-client-python
          path: dist

      - name: Publish package
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "better-hpc"
          repo: "keystone-api-client"
          file: "dist/keystone_api_client-${{ inputs.version }}.tar.gz"

  trigger-docs:
    name: Trigger Docs
    runs-on: ubuntu-latest

    environment:
      name: docs
      url: https://github.com/Better-HPC/keystone-docs

    steps:
      - name: Update docs
        uses: better-hpc/keystone-docs/.github/actions/update-action/@main
        with:
          keystone-gitops-id: ${{ secrets.KEYSTONE_GITOPS_ID }}
          keystone-gitops-pk: ${{ secrets.KEYSTONE_GITOPS_PK }}
          repo-name: keystone-python-client
          tag: v${{ inputs.version }}
